
export type Gsm = {
  _lang?: string,
  _morpho?: boolean,
  general: string,
  help: string,
  strictSearch: string,
  strictSearchTooltip: string,
  sortDate: string,
  sortDateTooltip: string,
  scrollTop: string,
  scrollTopTooltip: string,
  issuePrompt: string,
  issueDirective: string,
  areYouSure: string,
  showMore: string,
  notFound: string,
  data: string,
  sessionOnly: string,
  sessionOnlyTooltip: string,
  showImage: string,
  showImageTooltip: string,
  searchChats: string,
  search: string,
  language: string,
  context: string,
  contextTooltip: string,
  reset: string,
  clearCache: string,
  autoClear: string,
  autoClearTooltip: string,
  enableShortcut: string,
  enableShortcutTooltip: string,
  highlightColor: string,
  highlightColorTooltip: string,
  highlightBold: string,
  highlightBoldTooltip: string,
  advancedSearch: string,
  otherProjects: {
    header: string,
    askScreenshot: string,
    globalSpeed: string
  }
}